name: Deploy BTCstax to Hetzner

on:
  workflow_dispatch:

jobs:
  web-deploy:
    name: Build & Deploy BTCstax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Landingpage Code
        uses: actions/checkout@v4
        with:
          repository: aleks-83/btcstax-website
          token: ${{ secrets.GH_PAT }}
          path: btcstax-website

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install
        working-directory: ./btcstax-website

      - name: Build Project
        run: npm run build
        working-directory: ./btcstax-website

      - name: Generate index.html for Static Webhosting
        run: |
          JS_FILE=$(ls ./btcstax-website/.output/public/assets/index-*.js 2>/dev/null | head -n 1 | xargs -n 1 basename)
          CSS_FILE=$(ls ./btcstax-website/.output/public/assets/styles-*.css 2>/dev/null | head -n 1 | xargs -n 1 basename)

          cat <<EOF > ./btcstax-website/.output/public/index.html
          <!DOCTYPE html>
          <html lang="de">
            <head>
              <meta charset="UTF-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1.0" />
              <title>BTCstax</title>
              <link rel="stylesheet" href="/assets/${CSS_FILE}">
            </head>
            <body>
              <div id="root"></div>
              <script type="module" src="/assets/${JS_FILE}"></script>
            </body>
          </html>
          EOF

      - name: Sync Files to Hetzner FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: /public_html/btcstax/
          local-dir: ./btcstax-website/.output/public/
